[buildPlans.my-iosevka]
family = "My Iosevka"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

  [buildPlans.my-iosevka.variants]
  inherits = "ss05"

    [buildPlans.my-iosevka.variants.design]
    zero = "broken-slash"
    one = "base-flat-top-serif"
    four = "open"
    seven = "curly-serifed-crossbar"
    nine = "straight-bar"

    [buildPlans.my-iosevka.variants.italic]
    capital-a = "curly-top-serifed"
    capital-b = "standard-interrupted-unilateral-serifed"
    capital-c = "unilateral-serifed"
    capital-d = "standard-unilateral-serifed"
    capital-e = "top-left-serifed"
    capital-f = "top-left-serifed"
    capital-g = "toothed-inward-serifed-hookless"
    capital-h = "top-left-serifed"
    capital-i = "serifed"
    capital-j = "flat-hook-serifed"
    capital-k = "straight-top-left-serifed"
    capital-l = "motion-serifed"
    capital-m = "slanted-sides-hanging-motion-serifed"
    capital-n = "standard-motion-serifed"
    capital-p = "open-motion-serifed"
    capital-q = "detached-bend-tailed"
    capital-r = "standing-motion-serifed"
    capital-s = "unilateral-serifed"
    capital-t = "motion-serifed"
    capital-u = "tailed-serifless"
    capital-v = "straight-motion-serifed"
    capital-w = "straight-motion-serifed"
    capital-x = "curly-motion-serifed"
    capital-y = "straight-motion-serifed"
    capital-z = "cursive-with-horizontal-crossbar"
    a = "double-storey-serifed"
    b = "toothless-rounded-serifed"
    c = "unilateral-inward-serifed"
    d = "toothless-rounded-serifed"
    e = "rounded"
    f = "diagonal-tailed"
    g = "single-storey-serifed"
    h = "straight-top-left-serifed"
    i = "zshaped"
    j = "diagonal-tailed-serifed"
    k = "cursive-bottom-right-serifed"
    l = "serifed-diagonal-tailed"
    m = "short-leg-top-left-and-bottom-right-serifed"
    n = "tailed-serifed"
    p = "earless-corner-serifed"
    q = "earless-corner-straight-serifed"
    r = "corner-hooked-top-serifed"
    s = "unilateral-serifed"
    t = "diagonal-tailed-short-neck2"
    u = "tailed-motion-serifed"
    v = "cursive-serifed"
    w = "cursive-serifed"
    x = "curly-motion-serifed"
    y = "curly-motion-serifed"
    z = "cursive-with-horizontal-crossbar"
    zero = "broken-slash"
    one = "base-flat-top-serif"
    four = "open-non-crossing"
    seven = "curly-serifed-crossbar"
    lig-single-arrow-bar = "without-notch"

  [buildPlans.my-iosevka.ligations]
  inherits = "dlig"

[buildPlans.my-iosevka.widths.normal]
shape = 600
menu = 5
css = "normal"
