["pkg/helix"]
    type = "git-repo"
    url = "git@github.com:helix-editor/helix.git"
    refreshPeriod = "24h"

["pkg/yazi"]
    type = "git-repo"
    url = "git@github.com:sxyazi/yazi.git"
    refreshPeriod = "24h"
