[[snippets]]
prefix = "ppdebug"
scope = ["dart"]
body = 'print("🪲🪲🪲 - $1");'

[[snippets]]
prefix = "ppinfo"
scope = ["dart"]
body = 'print("🔵🔵🔵 - $1");'

[[snippets]]
prefix = "ppwarn"
scope = ["dart"]
body = 'print("🟡🟡🟡 - $1");'

[[snippets]]
prefix = "pperr"
scope = ["dart"]
body = 'print("🔴🔴🔴 - $1");'

[[snippets]]
prefix = "sl"
scope = ["dart"]
body = '''
import 'package:flutter/material.dart';

class $1 extends StatelessWidget {
    const $1({super.key});

    @override
    Widget build(BuildContext context) {
        return Container();
    }
}
'''

[[snippets]]
prefix = "sf"
scope = ["dart"]
body = '''
import 'package:flutter/material.dart';

class $1 extends StatefulWidget {
    const $1({super.key});

    @override
    State<$1> createState() => _$1State();
}

class _$1State extends State<$1> {

    @override
    void initState() {
      super.initState();
    }

    @override
    Widget build(BuildContext context) {
        return Container();
    }
}
'''
