format = '$character $git_branch $directory'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
home_symbol = ' '
truncation_length = 1
style = 'bold blue'

[git_branch]
symbol = ''
format = '\([$symbol$branch(:$remote_branch)]($style)\) '
